---
kind: Service
apiVersion: v1
metadata:
  name: goapp-app
spec:
  selector:
    app: goapp-app
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-app
spec:
  selector:
    matchLabels:
      app: goapp-app
  replicas: 2
  template:
    metadata:
      labels:
        app: goapp-app
    spec:
      containers:
      - name: goapp-app
        image: jtorresheredia/goapp:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: goapp-app-ingress-rules
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.aws-eks.be
    http:
      paths:
      - path: /
        backend:
          serviceName: goapp-app
          servicePort: 80
