---
kind: Service
apiVersion: v1
metadata:
  name: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 4
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: containous/whoami:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-app-ingress-rules
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: sample.aws-eks.be
    http:
      paths:
      - path: /
        backend:
          serviceName: sample-app
          servicePort: 80
