repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.10
    hooks:
      - id: tflint

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.43.0
    hooks:
    - id: terraform_fmt
    - id: terraform_docs

  - repo: git://github.com/pecigonzalo/pre-commit-terraform-vars
    rev: 8e947e99c45314397a8caacebefab44d74227b6b
    hooks:
    - id: terraform-vars
