---
kind: Service
apiVersion: v1
metadata:
  name: goapp-app
spec:
  selector:
    app: goapp-app
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-app
spec:
  selector:
    matchLabels:
      app: goapp-app
  replicas: 2
  template:
    metadata:
      labels:
        app: goapp-app
    spec:
      containers:
      - name: goapp-app
        image: containous/whoami:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
  name: external-auth-oauth2
  #namespace: kube-system
spec:
  rules:
  - host: api.aws-eks.be
    http:
      paths:
      - path: /oauth2/go
        backend:
          serviceName: goapp-app
          servicePort: 80
      - path: /
        backend:
          serviceName: oauth2-proxy
          servicePort: 4180
